Day 16: Introduction to NumPy   
Learn numpy arrays and basic operations  
Write a program that performs calculations on arrays of numbers  

In [1]:
import numpy as np

In [ ]:
numpy_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
numpy_array

(3, 3)

In [5]:
numpy_array.dtype

dtype('int64')

In [6]:
numpy_array.shape

(3, 3)

In [7]:
numpy_array.size

9

In [8]:
zeros = np.zeros((2,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
ones = np.ones((3,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
arr_r = np.arange(10)
arr_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr_d = np.linspace(1,5,10)
arr_d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
def calc_numbers(numbers):
    arr = np.array(numbers)
    return {
        'sum': np.sum(arr),
        'average': np.mean(arr),
        'max': np.max(arr),
        'min': np.min(arr)        
    }
    
data = [5, 10, 15, 20, 25]
results = calc_numbers(data)

print("Results:")
for key, value in results.items():
    print(f"{key.capitalize()}: {value}")


Results:
Sum: 75
Average: 15.0
Max: 25
Min: 5
